#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
is_public=$YNH_APP_ARG_IS_PUBLIC
path_url="/"
expire=$YNH_APP_ARG_EXPIRE
app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

ynh_webpath_available $domain $path_url
ynh_webpath_register $app $domain $path_url

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app expire $expire

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================

port=$(ynh_find_port 8095)
sudo yunohost firewall allow --no-upnp TCP $port 2>&1
ynh_app_setting_set $app port $port

#=================================================
# INSTALL NODEJS
#=================================================

ynh_install_nodejs $node_version

ynh_app_setting_set $app node_version $node_version

#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_app_setting_set $app final_path $final_path

#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================

ynh_system_user_create $app

#=================================================
# INSTALL ETHERCALC
#=================================================

ynh_use_nodejs

npm install -g ethercalc

#=================================================
# SETUP SYSTEMD BASED SERVICES
#=================================================

ynh_add_systemd_config

ynh_replace_string --match_string="__PORT__" --replace_string=$port --target_file=/etc/systemd/system/ethercalc.service
ynh_replace_string --match_string="__EXPIRE__" --replace_string=$expire --target_file=/etc/systemd/system/ethercalc.service
ynh_replace_string --match_string="__NODE_VERSION__" --replace_string=$node_version --target_file=/etc/systemd/system/ethercalc.service

cp ../conf/ethercalc.env /etc/systemd/system/ethercalc.env

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_systemd_action --service_name=ethercalc --action=enable

ynh_systemd_action --service_name=ethercalc --action=start

#=================================================
# GENERIC FINALIZATION
#=================================================

#=================================================
# SETUP LOGROTATE
#=================================================

ynh_use_logrotate

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

sudo yunohost service add $app --log "/var/log/ethercalc.log"

#=================================================
# SETUP SSOWAT
#=================================================

if [ $is_public -eq 0 ]
then	
	ynh_app_setting_delete $app skipped_uris
fi

if [ $is_public -eq 1 ]
then
	ynh_app_setting_set $app unprotected_uris "/"
fi

#=================================================
# RELOAD NGINX
#=================================================

ynh_systemd_action --service_name=nginx --action=reload
