#!/bin/bash

app="ethercalc"
name="ether"
name+="calc"

domain=$(sudo yunohost app setting $app domain)
# Remove nodejs
ynh_remove_nodejs
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -Rf /var/log/$name/$app.log*
sudo update-rc.d $app remove
sudo service $app stop
sudo rm /etc/init.d/$app
sudo yunohost service remove $app
sudo rm -f /var/www/$app

sudo userdel --remove $app

